FROM node:20-alpine

RUN apk add --no-cache dumb-init

WORKDIR /app

COPY package*.json ./

RUN npm ci && npm cache clean --force

COPY . .

EXPOSE 3001

ENTRYPOINT ["dumb-init", "--"]

CMD ["npm", "run", "start:dev"]